# Generated by Django 3.1.7 on 2021-04-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(default='', max_length=128, null=True)),
                ('username', models.CharField(default='', max_length=128, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('phone', models.CharField(default='0', max_length=11, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
