# Generated by Django 3.1.7 on 2021-05-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_self',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user')),
                ('icon', models.TextField(default='img/wp-1.jpg', null=True)),
                ('collects', models.TextField(default='', null=True)),
                ('user_subscribers', models.TextField(default='')),
                ('user_followers', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_like', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='user.user_self')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(default='')),
                ('user_receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiver', to='user.user_self')),
                ('user_sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender', to='user.user_self')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_name', models.CharField(max_length=64)),
                ('audio_create_time', models.TextField(max_length=64)),
                ('audio_like_num', models.IntegerField(default=0)),
                ('audio_link', models.TextField(default='', max_length=128)),
                ('audio_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_self')),
            ],
        ),
    ]
