# Generated by Django 3.1.7 on 2021-05-22 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_detail',
        ),
    ]
