# Generated by Django 3.1.7 on 2021-05-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('user', '0003_user_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user'),
        ),
    ]
