# Generated by Django 3.1.7 on 2021-05-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('user', '0005_auto_20210522_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiver', to='login.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender', to='login.user'),
        ),
    ]
