# Generated by Django 3.1.7 on 2021-05-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210522_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
