# Generated by Django 3.1.7 on 2021-05-22 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('user', '0007_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('user_receiver', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiver', to='login.user')),
                ('user_sender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='sender', to='login.user')),
            ],
        ),
    ]
