# Generated by Django 3.1.7 on 2021-05-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('user', '0008_user_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_self',
            name='user_followers',
        ),
        migrations.RemoveField(
            model_name='user_self',
            name='user_subscribers',
        ),
        migrations.CreateModel(
            name='User_subcriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TextField(max_length=64)),
                ('fol_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='follower', to='login.user')),
                ('sub_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='subscriber', to='login.user')),
            ],
        ),
    ]
