# Generated by Django 3.1.7 on 2021-05-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210526_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_review',
            name='time',
            field=models.TextField(default='', max_length=64),
        ),
    ]
